CREATE DATABASE IF NOT EXISTS airbnb;
USE airbnb;

CREATE TABLE NguoiDungTb (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    birthday VARCHAR(20),
    gender VARCHAR(10),
    role VARCHAR(20) DEFAULT 'USER',
    avatar VARCHAR(255),

    `deletedBy` INT NOT NULL DEFAULT 0,
	`isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
	`deletedAt` TIMESTAMP NULL DEFAULT NULL,
	`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ViTriTb (
    id INT PRIMARY KEY AUTO_INCREMENT,
    tenViTri VARCHAR(150) NOT NULL,
    tinhThanh VARCHAR(150),
    quocGia INT,
    hinhAnh VARCHAR(500),

    `deletedBy` INT NOT NULL DEFAULT 0,
	`isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
	`deletedAt` TIMESTAMP NULL DEFAULT NULL,
	`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE PhongTb (
    id INT PRIMARY KEY AUTO_INCREMENT,
    tenPhong VARCHAR(200) NOT NULL,
    khach INT DEFAULT 1,
    phongNgu INT DEFAULT 1,
    giuong INT DEFAULT 1,
    phongTam INT DEFAULT 1,
    moTa  VARCHAR(1000),
    giaTien INT NOT NULL,
    mayGiat BOOLEAN DEFAULT FALSE,
    banLa BOOLEAN DEFAULT FALSE,
    tiVi BOOLEAN DEFAULT FALSE,
    dieuHoa BOOLEAN DEFAULT FALSE,
    wifi BOOLEAN DEFAULT FALSE,
    bep BOOLEAN DEFAULT FALSE,
    doXe BOOLEAN DEFAULT FALSE,
    hoBoi BOOLEAN DEFAULT FALSE,
    banUi BOOLEAN DEFAULT FALSE,
    hinhAnh VARCHAR(500),
    viTri INT,
    FOREIGN KEY (viTri) REFERENCES ViTriTb(id),

    `deletedBy` INT NOT NULL DEFAULT 0,
	`isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
	`deletedAt` TIMESTAMP NULL DEFAULT NULL,
	`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE DatPhongTb (
    id INT PRIMARY KEY AUTO_INCREMENT,
    maPhong INT NOT NULL,
    ngayDen DATETIME NOT NULL,
    ngayDi DATETIME NOT NULL,
    soLuongKhach INT DEFAULT 1,
    maNguoiDat INT NOT NULL,
    FOREIGN KEY (maPhong) REFERENCES PhongTb(id),
    FOREIGN KEY (maNguoiDat) REFERENCES NguoiDungTb(id),

    `deletedBy` INT NOT NULL DEFAULT 0,
	`isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
	`deletedAt` TIMESTAMP NULL DEFAULT NULL,
	`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE BinhLuanTb (
    id INT PRIMARY KEY AUTO_INCREMENT,
    maCongViec INT NOT NULL,
    maNguoiBinhLuan INT NOT NULL,
    ngayBinhLuan DATETIME DEFAULT CURRENT_TIMESTAMP,
    noiDung VARCHAR(1000),
    saoBinhLuan INT DEFAULT 5,
    FOREIGN KEY (maCongViec) REFERENCES PhongTb(id),
    FOREIGN KEY (maNguoiBinhLuan) REFERENCES NguoiDungTb(id),

    `deletedBy` INT NOT NULL DEFAULT 0,
	`isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
	`deletedAt` TIMESTAMP NULL DEFAULT NULL,
	`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
